version: '3'

services:
    gogs:
      image: gogs/gogs:0.11.53
      restart: always
      volumes:
        # 将 gogs 的数据文件存储在本机
        - "./data/gogs:/data"
      ports:
        - "3000:3000"
      environment:
        - "RUN_CROND=true"
      depends_on:
        - postgres
    postgres:
      image: postgres:9.5
      restart: always
      volumes:
        # 将数据库文件存储到本机，以免丢失
        - "./data/postgresql:/var/lib/postgresql"
      ports:
        - "127.0.0.1:5432:5432"
      environment:
        # 数据库的连接信息
        - "POSTGRES_USER=admin"
        - "POSTGRES_PASSWORD=123456"
        - "POSTGRES_DB=gogs"
