pipeline:
  run:
    image: python:3.7-alpine3.8
    commands:
      - python3 test.py
  deploy:
    image: appleboy/drone-ssh
    host: linmu.date
    username: root
    secrets: [ ssh_key ]
    port: 22
    script:
      - cd /home/ubuntu/todo
      - git pull
      - sudo sh reload.sh
